require 'drb'

module TitlePage

  # a convenience class for accessing the SOAP API for http://www.titlepage.com.
  # Uses boilerplate code generated by soap4r.
  #
  # You should be aware of any limits of query volume imposed by the provider - currently a
  # maximum of 30 queries per minute is permitted.
  #
  # For a basic usage overview, check out RBook::TitlePage
  class Client

    # Optional driver parameter allows an alternative SOAP driver to the default to be specified.
    # This is primarily for testing purposes and probably isn't useful to anyone in the real world.
    def initialize
      @driver = TitleQueryPortType.new
      @token  = nil
    end

    # login to the titlepage API.
    def login(username, password)
      raise InvalidRubyVersionError, 'Ruby 1.8.3 or higher is required to use this class' unless RUBY_VERSION >= "1.8.3"
      logout if @token
      @token = @driver.login(username, password)
      if @token
        return true
      else
        return false
      end
    end

    # logout from the titlepage API
    def logout
      if @token
        @driver.logout(@token)
        @token = nil
      end
    end

    # retrieve information on a specified ISBN
    def find(isbn)
      return NotLoggedInError, 'You must login to titlepage API before performing a search' unless @token
      isbn = RBook::ISBN::convert_to_isbn13(isbn)
      return nil if isbn.nil?
      begin
        result = @driver.SearchByISBN13(@token, isbn)

        if result.Product.nil?
          return nil
        else
          return result
        end
      end
    end

    # a convenience method to make single queries to title page a little cleaner. 
    #
    #  result = RBook::TitlePage.find("username","password","9780091835132")
    #  puts result.inspect
    def self.find(username, password, isbn)
      result = nil
      RBook::TitlePage::Client.open(username, password) do |tp|
        result = tp.find(isbn)
      end
      return result
    end

    # a convenience method to make queries to title page a little cleaner. This function
    # essentially calls the login and logout functions for you automatically.
    #
    #  RBook::TitlePage.open("username","password") do |tp|
    #    result = tp.find("9780091835132")
    #  end
    def self.open(username, password)

      tp = self.new

      begin
        tp.login(username, password)

        yield(tp)

      ensure
        tp.logout
      end
    end

  end
end
