$LOAD_PATH.unshift("/../")

# the soap4r gem is often a little better than the version that lives in
# the ruby standard library, so if the local system has the gem installed 
# use that
begin
  gem 'soap4r'
rescue LoadError => e
  # do nothing
end

require 'rubygems'
require 'rbook/isbn'
require File.dirname(__FILE__) + '/titlepage/titlepage_driver'
require File.dirname(__FILE__) + '/titlepage/titlepage_utils'
require File.dirname(__FILE__) + '/titlepage/mapping_registry'
require File.dirname(__FILE__) + '/titlepage/client'
require File.dirname(__FILE__) + '/titlepage/wwwclient'

# a convenience module for accessing the SOAP API for http://www.titlepage.com.
# Uses boilerplate code generated by soap4r.
#
# You should be aware of any limits of query volume imposed by the provider - currently a
# maximum of 30 queries per minute is permitted.
#
# All examples require the following two lines at the top of your file:
#   require 'rubygems'
#   require 'rbook/titlepage'
#
# Basic usage:
#  tp = RBook::TitlePage::Client.new
#  tp.login('someuser','topsecret')
#  puts tp.find("0091835135").inspect
#  sleep 3
#  puts tp.find("9780672327568").inspect
#  tp.logout
#
# Alternative Usage:
#  RBook::TitlePage::Client.open("username","password") do |tp|
#    puts tp.find("0091835135").inspect
#    sleep 3
#    puts tp.find("9780672327568").inspect
#  end
module TitlePage
  class InvalidRubyVersionError < RuntimeError;end;
  class NotLoggedInError < RuntimeError;end;
end
